/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package caseinfo;

import java.awt.Container;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Prabhu
 */
public class Login extends javax.swing.JFrame {
    
    
  
    

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
    }

    private Login(Login ch) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        ImageArea = new javax.swing.JLabel();
        LoginSubmit = new javax.swing.JButton();
        Heading = new javax.swing.JLabel();
        password_lable = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Case Details");
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(200, 200, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 500));
        setResizable(false);

        panel.setBackground(new java.awt.Color(204, 204, 204));
        panel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        panel.setMaximumSize(new java.awt.Dimension(800, 500));
        panel.setMinimumSize(new java.awt.Dimension(800, 500));
        panel.setName(""); // NOI18N
        panel.setPreferredSize(new java.awt.Dimension(800, 500));
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelMouseMoved(evt);
            }
        });

        ImageArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caseinfo/Background.png"))); // NOI18N
        ImageArea.setText("jLabel5");
        ImageArea.setAutoscrolls(true);
        ImageArea.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        ImageArea.setMaximumSize(new java.awt.Dimension(600, 500));
        ImageArea.setMinimumSize(new java.awt.Dimension(600, 500));
        ImageArea.setPreferredSize(new java.awt.Dimension(600, 500));

        LoginSubmit.setBackground(new java.awt.Color(204, 204, 255));
        LoginSubmit.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        LoginSubmit.setText("Login");
        LoginSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginSubmitMouseClicked(evt);
            }
        });
        LoginSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginSubmitActionPerformed(evt);
            }
        });

        Heading.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Heading.setForeground(new java.awt.Color(0, 0, 102));
        Heading.setText("Login");

        password_lable.setForeground(new java.awt.Color(0, 0, 102));
        password_lable.setText("Password");

        username_label.setForeground(new java.awt.Color(0, 0, 102));
        username_label.setText("Username");

        username.setBackground(new java.awt.Color(153, 255, 203));

        password.setBackground(new java.awt.Color(153, 255, 203));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(ImageArea, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Heading)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username_label, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(password_lable, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LoginSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(username)
                            .addComponent(password))))
                .addGap(33, 33, 33))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImageArea, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Heading)
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(username_label)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password_lable)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(LoginSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginSubmitActionPerformed
        
         try {
            
            String uName = username.getText();//retrieve value
            String pword = password.getText();
            
            String uname = URLEncoder.encode("user", "UTF-8") + "=" + URLEncoder.encode(uName, "UTF-8");
            String pass = URLEncoder.encode("password", "UTF-8") + "=" + URLEncoder.encode(pword, "UTF-8");
                String LoginData = uname + "&" + pass;
                JOptionPane.showMessageDialog(null, LoginData);
            
            String inLine;  
          
            URL u1 = new URL("http://www.locurasystems.com/CaseInfo/public/login");  
            URLConnection uc1 = u1.openConnection();
            uc1.setDoOutput(true);  
            OutputStreamWriter out = new OutputStreamWriter(uc1.getOutputStream());  
            out.write(LoginData);
            //System.out.println("before ");
            out.flush();
            //System.out.println("after");
            try (BufferedReader in = new BufferedReader( new InputStreamReader( uc1.getInputStream() ) )) {
                while ((inLine = in.readLine()) != null) {
                    System.out.println(inLine);
                  //JOptionPane.showMessageDialog(null, inLine);
                    switch (inLine) {
                        case "Login Successfull":
                            JOptionPane.showMessageDialog(null, "your login is successfull");
                            HomePage home = new HomePage();
                            home.setVisible(true);
                            break;
                        case "Failed login":
                            Validate validate = new Validate();
                            validate.setVisible(true);
                            break;
                            
                       
                            
                        default:
                            dispose();
//                      
                            break;
                    }
                  
                  //new Login().setVisible(false);
                  
                  //dispose();
                 
                  
                }
                
            }  
            
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_LoginSubmitActionPerformed

    private void LoginSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginSubmitMouseClicked

    }//GEN-LAST:event_LoginSubmitMouseClicked

    
    
    

    
    
    private void panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMouseClicked

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        

        
    }//GEN-LAST:event_panelMouseDragged

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        
           
        
        
    }//GEN-LAST:event_panelMousePressed

    private void panelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
//        Login frame = new Login();
//    //frame.setPreferredSize(new Dimension(300, 280));
//
//    Login ch = new Login();
//    frame.getContentPane().add(ch);
    //frame.setUndecorated(true);

//    Login mml = new Login(ch);
//    ch.addMouseListener((MouseListener) mml);
//    ch.addMouseMotionListener((MouseMotionListener) mml);

//    frame.pack();
//    frame.setVisible(true);
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel ImageArea;
    private javax.swing.JButton LoginSubmit;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel password_lable;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
